version: '3'

tasks:
  lint:
    cmds:
      - poetry run black .
      - poetry run isort .
      - poetry run flake8 .
    desc: format and validate code using linters

  build:
    cmds:
      - pip install --upgrade pip=={{.PIP_VERSION}}
      - pip install --upgrade poetry=={{.POETRY_VERSION}}
      - poetry env use {{.PYTHON_VERSION}}
      - poetry install
    desc: setup toolchain

  run-server:
    cmds:
      - poetry run uvicorn user_management.main:app --host 0.0.0.0 --port 8000
    desc: run development server

  db-migrate:
    cmds:
      - poetry run alembic upgrade head
    desc: migrate db
    run: once

  run-tests:
    cmds:
      - poetry run pytest -s
    desc:
      run tests

vars:
  PIP_VERSION:
    sh: cat .env | grep PIP_VERSION | sed -e 's/^.*=//g'
  POETRY_VERSION:
    sh: cat .env | grep POETRY_VERSION | sed -e 's/^.*=//g'
  PYTHON_VERSION:
    sh: cat .env | grep PYTHON_VERSION | sed -e 's/^.*=//g'
