version: '3'

tasks:
  code-format:
    cmds:
      - poetry run black .
      - poetry run isort .
    desc: format code with black, isort

  code-lint:
    cmds:
      - poetry run flake8 .
      - poetry run black . --check
      - poetry run isort . --check
    desc: validate code using linters

  build:
    cmds:
      - pip install --upgrade "pip==23.3.1"
      - pip install --upgrade "poetry==1.6.1"
      - poetry env use python3.10
      - poetry install
    desc: setup toolchain

  run-server:
    cmds:
      - poetry run uvicorn user_management.main:app --host 0.0.0.0 --port 8000
    desc: run development server

  db-migrate:
    cmds:
      - poetry run alembic upgrade head
    desc: migrate db
    run: once
