version: '3'

tasks:
  lint:
    cmds:
      - poetry run black .
      - poetry run isort .
      - poetry run flake8 .
    desc: format and validate code using linters

  build:
    cmds:
      - pip install --upgrade pip=={{.PIP_VERSION}}
      - pip install --upgrade poetry=={{.POETRY_VERSION}}
      - poetry env use {{.PYTHON_VERSION}}
      - poetry install
    desc: setup toolchain

  run-server:
    cmds:
      - poetry run uvicorn user_management.main:app --host 0.0.0.0 --port 8000
    desc: run development server

  db-migrate:
    cmds:
      - poetry run alembic upgrade head
    desc: migrate db
    run: once

  run-tests:
    cmds:
      - poetry run pytest -s
    desc:
      run tests

  docker-build:
    cmds:
      - docker compose build --no-cache
    desc: build webapp image
    run: once

  docker-up:
    cmds:
      - docker compose up --detach --remove-orphans
    desc: start all services
    run: once

  docker-db-migrate:
    cmds:
      - docker compose exec webapp bash
      - alembic upgrade head
    desc: migrate db inside container
    run: once

  docker-down:
    cmds:
      - docker compose down --remove-orphans
    desc: stop all services
    run: once

  clean:
    cmds:
      - docker compose down --remove-orphans || exit 0
      - rm -rf .local/services
      - rm -rf .pytest_cache
    desc: cleans dev environment, removes containers, volumes, caches
    run: once

vars:
  PIP_VERSION:
    sh: cat .env | grep PIP_VERSION | sed -e 's/^.*=//g'
  POETRY_VERSION:
    sh: cat .env | grep POETRY_VERSION | sed -e 's/^.*=//g'
  PYTHON_VERSION:
    sh: cat .env | grep PYTHON_VERSION | sed -e 's/^.*=//g'
